package Menus.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class CustomMenuSubgroup1_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "Menus.plugin.CustomMenuSubgroup1_ActionGroup";
  public static final String LABEL_ID_upper = ID + "upper";
  public static final String LABEL_ID_lower = ID + "lower";

  public CustomMenuSubgroup1_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("CustomMenuSubgroup1", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    addNamedAnchor(LABEL_ID_upper);
    CustomMenuSubgroup1_ActionGroup.this.addSeparator();
    addNamedAnchor(LABEL_ID_lower);
  }
}
