package Menus.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class CustomActionGroupForAction1_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "Menus.plugin.CustomActionGroupForAction1_ActionGroup";

  public CustomActionGroupForAction1_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("CustomActionGroupForAction1", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    CustomActionGroupForAction1_ActionGroup.this.addAction("Menus.plugin.CustomAction1_Action");
  }
}
