package Menus.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class CustomActionGroupForAction2_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "Menus.plugin.CustomActionGroupForAction2_ActionGroup";

  public CustomActionGroupForAction2_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("CustomActionGroupForAction2", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    CustomActionGroupForAction2_ActionGroup.this.addAction("Menus.plugin.CustomAction2_Action");
  }
}
