package Menus.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class CustomMenuGroup1_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "Menus.plugin.CustomMenuGroup1_ActionGroup";
  public static final String LABEL_ID_start = ID + "start";
  public static final String LABEL_ID_submenu = ID + "submenu";
  public static final String LABEL_ID_end = ID + "end";

  public CustomMenuGroup1_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("CustomMenuGroup1", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    CustomMenuGroup1_ActionGroup.this.addSeparator();
    addNamedAnchor(LABEL_ID_start);
    addNamedAnchor(LABEL_ID_submenu);
    addNamedAnchor(LABEL_ID_end);
  }
}
